name: Docker Build And Push
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
env:
  REPO: gdh-project/auth

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: login into github package container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{env.REPO}}:latest,ghcr.io/${{env.REPO}}:${{github.ref_name || github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max