name: Release And Deploy
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: login into github package container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: RUN GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    needs: goreleaser
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{secrets.SERVICE_ID}}
      RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
    steps:
      - name: deploy new docker image
        run: railway redeploy -s ${{env.SVC_ID}} -y

